project_id = "srwdikhfrfdmhlfdklzj"

[functions.track-click]
verify_jwt = false

[functions.discord-oauth-callback]
verify_jwt = false

[functions.paradise-webhook]
verify_jwt = false

[functions.track-referral]
verify_jwt = false

[functions.bot-api]
verify_jwt = false
